### ISSUE TITLE
Warning: Track download failed: list index out of range

### ISSUE THREAD

**Issue by thejimbo21** [yarrm80s/orpheusdl-napster#2]
dont know what happened 
example 
 https://cdn.discordapp.com/attachments/1032405466346696766/1032405476303978506/unknown.png

**Comment by OrfiDev** [comment]
Please retry the same download with debug mode turned on in the settings, and send the output of that instead, as it gives us a much better error message

**Comment by thejimbo21** [comment]
hello i have fixed it it was just my account ran out thats all thanks for the response tho
